In [134]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [135]:
!ls

attacks.csv  main.py  notebook.ipynb  README.md

In [136]:
pd.set_option("display.max_columns", 120)

In [137]:
data= pd.read_csv("../data-cleaning/attacks.csv", encoding='Windows-1252' )

In [138]:
data.head(200)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2016.12.11.a,11-Dec-2016,2016.0,Invalid,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Shane Garthwait,M,19,Cuts to right ankle & foot,NaN,Afternoon,Shark involvement not confirmed,"News Journal, 12/15/2016",2016.12.11.a-Garthwait.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.12.11.a,2016.12.11.a,6108.0,NaN,NaN
196,2016.12.06,06-Dec-2016,2016.0,Provoked,AUSTRALIA,New South Wales,Merimbula,Surf fishing,Jesse Phillips,M,20,Lacerations to both hands while attempting to ...,N,02h00,"Wobbegong shark, 2m",Bay 93.9 Geelong,2016.12.06-Phillips.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.12.06,2016.12.06,6107.0,NaN,NaN
197,2016.12.01,01-Dec-2016,2016.0,Unprovoked,AUSTRALIA,New South Wales,Booti Booti National Park,Surfing,Colin Rowland,M,65,Injuries to foot & arm,N,09h00,White shark,"B. Myatt, GSAF",2016.12.01-Rowland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.12.01,2016.12.01,6106.0,NaN,NaN
198,2016.11.28,28-Nov-2016,2016.0,Provoked,AUSTRALIA,Victoria,Queenscliff,Fishing,Rod McFarlane,M,73,Laceration to right hand by hooked & gaffed sh...,N,11h00,"Broadnose sevengill shark, 1.5 m","ABC News, 11/28/2016",2016.11.28-Fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.11.28,2016.11.28,6105.0,NaN,NaN
199,2016.11.14,14-Nov-2016,2016.0,Unprovoked,USA,Hawaii,"Kamaole Beach Park I, Maui",Floating,Barbara Zawacki,F,58,Injuries to right calf and thigh,N,10h30,Tiger shark,"Maui News, 11/14/2016",2016.11.14-Zawacki.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.11.14,2016.11.14,6104.0,NaN,NaN

In [139]:
data.describe()

              Year  original order
count  6300.000000     6309.000000
mean   1927.272381     3155.999683
std     281.116308     1821.396206
min       0.000000        2.000000
25%    1942.000000     1579.000000
50%    1977.000000     3156.000000
75%    2005.000000     4733.000000
max    2018.000000     6310.000000

In [140]:
data.sample(30)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
25018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7902,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2567,1992.01.23,23-Jan-1992,1992.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Isipingo,Swimming,Noor-Mubeen Shaik,M,19,Right foot lacerated,N,17h30,"Zambesi shark, 1.7 m [5.5']","G. Cliff, NSB",1992.01.23-Shaik.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1992.01.23,1992.01.23,3736.0,NaN,NaN
17130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2539,1992.08.21,21-Aug-1992,1992.0,Invalid,USA,Hawaii,"Twin Arches, Hana Ranch, Maui",Fell from cliff while fishing & disappeared in...,Chester N. Shishido,M,NaN,Body recovered next morning. Injuries appeared...,NaN,15h00,Questionable incident,"J. Borg, p.82; L. Taylor (1993), pp.114-115",1992.08.21-Shishido.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1992.08.21,1992.08.21,3764.0,NaN,NaN
24889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5711,1890.00.00.a,Ca. 1890,1890.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Cape Vidal,Bathing,Zulu boy,M,NaN,"FATAL, leg bitten, foot partly severed",Y,15h30,NaN,"J. Daniel, M. Levine, GSAF",1890.00.00.a-ZuluMale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1890.00.00.a,1890.00.00.a,592.0,NaN,NaN
2156,1998.10.24,24-Oct-1998,1998.0,Unprovoked,USA,Florida,"Jupiter Beach, Palm Beach County",Swimming,Jessica Stephens,F,17,Minor lacerations on right ankle & foot,N,Afternoon,NaN,"Sun Sentinel.Â Fort Lauderdale, 10/25/1998, p.3B",1998.10.24-Stephens.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.10.24,1998.10.24,4147.0,NaN,NaN
8674,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760,2003.07.00.c,Jul-2003,2003.0,Unprovoked,USA,Florida,"Fort Lauderdale, Broward County",Spearfishing,Mark Marks,M,NaN,Laceration to toe,N,NaN,8' great hammerhead shark,M. Marks,2003.07.00.c-MarkMarks.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.00.c,2003.07.00.c,4543.0,NaN,NaN
22594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3361,1971.06.30,30-Jun-1971,1971.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Mossel Bay,Surfing,Gideon Scheltema,M,21,Leg & surfboard bitten,N,15h35,"White shark, 3 m [10'], species identity confi...","G. Scheltema, M. Levine, GSAF; J. Bass, ORI",1971.06.30-Scheltema.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1971.06.30,1971.06.30,2942.0,NaN,NaN
16396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4200,1957.04.28,28-Apr-1957,1957.0,Unprovoked,USA,California,"Atascadero Beach, Morro Bay, San Luis Obispo C...",Swimming,Peter Savino,M,25,"FATAL, seen with arm in mouth of shark. Body n...",Y,13h30,White shark,"D. Miller & R. Collier, R. Collier, pp.16-17; ...",1957.04.28-Savino_Collier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1957.04.28,1957.04.28,2103.0,NaN,NaN

In [141]:
to_drop = ['Unnamed: 22', 'Unnamed: 23']
data.drop(to_drop, inplace=True, axis=1)

In [142]:
data.sample(3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
1248,2008.06.20,20-Jun-2008,2008.0,Unprovoked,USA,Florida,"Fernandina Beach, Nassau County",Wading,Jennifer Cation,F,35,Lacerations to lower right calf,N,11h10,NaN,"News-Leader, 6/21/2008",2008.06.20-Cation.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.06.20,2008.06.20,5055.0
5441,1907.12.21,21-Dec-1907,1907.0,Unprovoked,AUSTRALIA,New South Wales,"Middle Harbour, Sugarloaf Bay, Sydney (Estuary)",Bathing,Henry Jones,M,NaN,FATAL,Y,NaN,Bull shark,"R.D. Weeks, GSAF; Otago Daily Times, 12/24/1907",1907.12.21-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1907.12.21,1907.12.21,862.0
16595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
data['href']

0        http://sharkattackfile.net/spreadsheets/pdf_di...
1        http://sharkattackfile.net/spreadsheets/pdf_di...
2        http://sharkattackfile.net/spreadsheets/pdf_di...
3        http://sharkattackfile.net/spreadsheets/pdf_di...
4        http://sharkattackfile.net/spreadsheets/pdf_di...
                               ...
25718                                                  NaN
25719                                                  NaN
25720                                                  NaN
25721                                                  NaN
25722                                                  NaN
Name: href, Length: 25723, dtype: object

In [144]:
to_drop = ['href', 'href formula']
data.drop(to_drop, inplace=True, axis=1)
# he borrado las columnas porque los enlaces no tenian contenido y el resto de filas eran nan

In [145]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
data.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
Case Number.1              object
Case Number.2              object
original order            float64
dtype: object

In [149]:
df.isnull().sum()

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
Case Number.1             19421
Case Number.2             19421
original order            19414
dtype: int64

In [148]:
data.fillna(df.filter(like='20').quantile(.8, axis = 1), axis=0, inplace=True)

In [152]:
df.Country

0              USA
1              USA
2              USA
3        AUSTRALIA
4           MEXICO
           ...
25718          NaN
25719          NaN
25720          NaN
25721          NaN
25722          NaN
Name: Country, Length: 25723, dtype: object